all_discipline = {
    #ANIMALISM
    'bond famulus':"Create an enhanced animal companion.\nDice: Charisma + Animal Ken.\nVampires may only have one famulus but you can make animal ghouls without this.",
    'sense the beast':'Sense hostility and supernatural traits.\nDice: Resolve + Animalism vs Composure + Subterfuge\n.This power can also be used actively.',
    'animal messenger':'Use a Famulus to send a message to someone.\nAmalgam: Auspex ●.\nThe Famulus must test Resolve + Streetwise/Survival if targets location is unknown against a diff 2 or Intelligence + Streetwise/Survival if the target is actively hiding.',
    'atavism':'	Revert animals to their base and primal instinct\nDice: Composure + Animalism\nThe target must be able to sense the user for this power to work.',
    'feral whispers':'Two-way communication with animals or summoning.\nDice Manipulation/Charisma + Animalism\nThe cost is free if used on their Famulus.',
    "messenger's command":"Use Compel or Mesmerize through a Famulus.\nAmalgam: Dominate ●.",
    "messenger command":"Use Compel or Mesmerize through a Famulus.\nAmalgam: Dominate ●.",
    "messengers command":"Use Compel or Mesmerize through a Famulus.\nAmalgam: Dominate ●.",
    'animal succulence':"Slake additional hunger from animals and counts Blood Potency as 2 levels lower in regards to slaking penalties. This will never let the character slake to 0",
    'plague of beasts':'Mark an individual as a target of animal attention.\nDice: Manipulation + Animalism vs Composure + Animal Ken\nThe target takes the margin of the win as a penalty against Skill pools except Physical, this also makes them easier to track down.',
    'quell the beast':'Force a vampires beast to slumber or make a mortal lethargic.\nDice: Charisma + Animalism vs Stamina + Animalism\nAgainst Vampires this lasts several turns equal to test margin +1.',
    'scent of prey':'Track a mortal down who has witnessed a masquerade breach.\nDice: Resolve + Animalism\nIt lasts one night if Critical Win.',
    'unliving hive':'Extends Animalism influence to swarms of insects.\nAmalgam: Obfuscate ●●\nSwarms are treated as single creatures.',
    'subsume the spirit':'Possess the body of an animal.\nDice: Manipulation + Animalism\nThe cost is free if used on their Famulus',
    'sway fhe flock':'Influence animals within an area to behave a certain way.\nDice: Composure + Animalism\nThe amount of successes determine how influenced the animals are, the Disciplines range can be increased per Rouse Check.',
    'animal sominion':'Command flocks or packs of animals.\nDice: Charisma + Animalism\nThis power does not summon animals, instead utilizing those already present.',
    'coax the bestial temper':'Either increase or decrease the Difficulty to resist Frenzy for vampires nearby.\nDice: Manipulation + Animalism\nEach success of margin increases or decreases the difficulty',
    'drawing out the beast':'Transfer their terror or fury frenzy to a nearby victim.\nDice: Wits + Animalism\nThis power cannot transfer Hunger Frenzy.',

    #AUSPEX
    'heightened senses':'Enhance vampiric senses and add Auspex rating to all perception rolls.\nDice: Wits + Resolve\nHaving the power activated for long periods might require the use of Willpower.',
    'sense the unseen':"Sense supernatural activity.\nDice: Wits/Resolve + Auspex\nIf the target is using Obfuscate they oppose using Wits + Obfuscate vs the user's Wits + Auspex, normal searches use Resolve.",
    "panacea":'Heals Willpower and calms nerves.\nDice: Composure + Auspex\nAmalgam: Fortitude ●\nIf the user uses this on more than one subject on the same night, the cost increases to spend Willpower equal to half the number of successes in the margin per additional target.',
    "obeah":'Heals Willpower and calms nerves.\nDice: Composure + Auspex\nAmalgam: Fortitude ●\nIf the user uses this on more than one subject on the same night, the cost increases to spend Willpower equal to half the number of successes in the margin per additional target.',
    'premonition':'Visions of the future.\nDice: Resolve + Auspex\n	The Storyteller may activate this power passively with no cost, when used actively the user must make a Rouse Check and roll Resolve + Auspex.',
    'reveal temperament':'Smell the Resonance of a target and/or if Dyscrasia is present.\nDice: Intelligence + Auspex vs Composure + Subterfuge\nWhen used on Kindred this reveals information about their last feed.',
    'unerring pursuit':'Tracking a victim.\nDice: Resolve + Auspex\nAmalgam: Dominate ●\nThe victim can roll Wits + Awareness to catch a glimpse of the user once under its effects.',
    'eyes of beasts':'Share the senses with animals.\nAmalgam: Animalism\nThis power works through groups of animals.',
    'fatal flaw':'Find the weakness of a target.\nDice: Intelligence + Auspex vs Composure/Stamina + Subterfuge\nAmalgam: Oblivion ●\nIt can be defended against with Composure for mental weaknesses or with Stamina for physical.',
    'scry the soul':"Perceives information about the target.\nDice: Intelligence + Auspex vs Composure + Subterfuge\nThis can either be used on a single target or a crowd.",
    'share the senses':"Tapping into other's senses.\nDice: Resolve + Auspex\nSense the Unseen can allow the user to be noticed by the victim.",
    "spirit's touch":"Gathering emotional residue from an object or location\nDice: Intelligence + Auspex\nWhat information they gleam works from the most recent backward.",
    "spirits touch":"Gathering emotional residue from an object or location\nDice: Intelligence + Auspex\nWhat information they gleam works from the most recent backward.",
    'clairvoyance':'Information gathering from surroundings.\nDice: Intelligence + Auspex\nThis power can be used to monitor events in progress.',
    'possession':"Possess a mortal body.\nDice: Resolve + Auspex vs Resolve + Intelligence\nAmalgam: Dominate ●●●\nThis power does not give the ability to read the target's mind, use their skills or impersonate them.",
    'telepathy':"Read minds and project thoughts.\nDice: Resolve + Auspex vs Wits + Subterfuge\nThe user doesn't need to roll to project their thoughts onto others.",
    'unburdening the bestial soul':"Stain removal or protection from Stains\nDice: 	Composure + Auspex\nAmalgam: Dominate ●●●\nPrerequisite: Panacea\nThis power only works on vampires with a lower Humanity rating.",
    
    #BLOOD SORCERY
    "corrosive vitae":"Turn vitae corrosive. Does not work against unliving flesh, such as other vampires.",
    "shape the sanguine sacrament":	"Shape blood into a shape or image.\nDice: Manipulation + Blood Sorcery.\bthe user uses their vitae, it costs one Rouse Check.",
    "a taste for blood":"Discover traits of another through their blood.\nDice: Resolve + Blood Sorcery",
    "extinguish vitae":"In use, this increases another Kindred's Hunger.\nDice: Intelligence + Blood Sorcery vs Stamina + Composure\nThe victim can determine who used this power against them if they can see them and win an Intelligence + Occult vs Wits + Subterfuge roll.",
    "scour secrets":"Pour through a large amount of content within minutes.\nDice: Intelligence + Blood Sorcery\nThis power does not allow the user to parse things written in a language they cannot understand.",
    "blood of potency":"Increase Blood Potency temporarily.\nDice: Resolve + Blood Sorcery\nThis power can allow a Kindred to bypass the Blood Potency limit set by their generation",
    "scorpion's touch":	"Change own vitae into paralyzing poison.\nDice: Strength + Blood Sorcery vs Stamina +Occult/Fortitude\nA mortal who takes any damage from this will go unconscious.",
    "scorpions touch":	"Change own vitae into paralyzing poison.\nDice: Strength + Blood Sorcery vs Stamina +Occult/Fortitude\nA mortal who takes any damage from this will go unconscious.",
    "transitive bond":	"Extend the properties of Blood Bonding in vitae. This power was developed originally by the Tremere to combat their bane to only resurface within the Sabbat.",
    "ripples of the heart":"Manipulate the blood or Blood of others. This power can inflict Compulsions on others who feed from the infected or alter the Resonance of a mortal.",
    "theft of vitae":"Manipulate blood from a victim through the air to feed.\nDice: Wits + Blood Sorcery vs Wits +Occult\n When in use the victim is under the same influence as a standard Kiss.",
    "blood aegis":"Form a protective Blood barrier. For each Rouse Check, the user can reduce the damage taken by five points.",
    "baal's caress":"Change the user's own Vitae into an aggressive and lethal poison.\nDice: Strength + Blood Sorcery vs Stamina +Occult/Fortitude\nIf a mortal takes one point of damage they die instantly.",
    "baals caress":"Change the user's own Vitae into an aggressive and lethal poison.\nDice: Strength + Blood Sorcery vs Stamina +Occult/Fortitude\nIf a mortal takes one point of damage they die instantly.",
    "cauldron of blood":"Boil the victim's blood in their body.\nDice: Resolve + Blood Sorcery vs Composure +Occult/Fortitude\n If a mortal takes one point of damage they die screaming.",
    "reclamation of vitae":	"Reclaim the Blood given to create ghouls over distance. Those outside of the Sabbat take stains upon use.",

    #BLOOD SORCERY RITUALS
    "astromancy":"Learn information such as Skills, Desires and Convictions about someone. \nDice: Intelligence + Blood Sorcery\nIf you know the correct Birth or Embrace date, you can add 1 die to the Ritual pool. This does not stack if you know both.",
    "beelzebeatit":	"Animals avoid the area.\nDice: Intelligence + Blood Sorcery\nNothing prevents directed or controlled creatures from entering.",
    "bind theaAccusing tongue":	"Prevent someone from communicating something negative about the caster\nDice: Intelligence + Blood Sorcery\nVictim can break free by rolling Composure + Resolve.",
    "blood walk":"Learn characters generation, name, and sire.\nDice: Intelligence + Blood Sorcery\nRequires one Rouse Check from the subject to be performed.",
    "bloody message":"Make a message appear to a specific type of person then disappear once read.\nDice: Intelligence + Blood Sorcery\nMake the Ritual Roll when enchanting the surface.",
    "clinging of the insect":"Cling to walls like an insect.\nDice: Intelligence + Blood Sorcery\n The user must cling with both their hands and feet.",
    "coax the garden":"Use plant life to defend.\nDice: Intelligence + Blood Sorcery\nThe plants will target anyone who isn't the caster.",
    "craft bloodstone":	"Craft a tracking stone.\nDice: Intelligence + Blood Sorcery\nA caster may have up to as many stones as they have Resolve.",
    "douse the fear errata":"Remove their fear of fire temporarily.\nDice: Intelligence + Blood Sorcery\nThe power wears off once the scene ends.",
    "enrich the blood":"Make a mortal more nourishing.\nDice: Intelligence + Blood Sorcery\nThis does not work on Kindred vitae.",
    "herd ward":"Level 1(Minor): Ward a single kine of a herd to prevent unauthorized feeding.\nDice: Intelligence + Blood Sorcery\nMake the Ritual Roll when someone else feeds off the herd.\n\nLevel 3 (Major): Ward a herd against unauthorized feeding by warding the door to protect multiple people within.\nDice: Intelligence + Blood Sorcery\nMake the Ritual Roll when someone else feeds off the herd.",
    "letter ward":"Place a ward on a letter\nDice: Intelligence + Blood Sorcery\nMake the Ritual Roll if anyone other than the intended recipient opens it.",
    "seal the brand":"Make a tattoo permanent on a vampire.\nDice: Intelligence + Blood Sorcery\nThe process inflicts 1 Superficial damage",
    "wake with evening's freshness":"Awakens the caster at any signs of danger during day sleep.\nDice: Intelligence + Blood Sorcery\n	Do not make the Ritual roll until true danger appears.",
    "ward against ghouls":"Protect themselves against Ghouls.\nDice: Intelligence + Blood Sorcery\nUses standard rules for Wards.",
    "blood apocrypha":"Embed messages into Blood or vessels.\nDice:	Intelligence + Blood Sorcery\nThe first person receives the message if they are the intended recipient or if they have A Taste For Blood.",
    #lEVEL 2
    "as fog on water":	"Walk on water silently.\nDice: Intelligence + Blood Sorcery\nThis can be ended early or kept to allow them to walk on water for the rest of the night.",
    "calling the aura's remnants":"Speak with the residual aura of someone who has died.\nDice: Intelligence + Blood Sorcery\nThe aura only has memories up to the time of death.",
    "calix secretus":"Store vitae for a later use.\nDice: Intelligence + Blood Sorcery\nTwo Rouse Checks stored will slake one Hunger.",
    "communicate with kindred sire":"Creates a long-distance telepathic link between Sire and Childe\nDice: Intelligence + Blood Sorcery\nMajor disturbance on either side breaks the connection.",
    "craftmaster":"Temporarily gain dots and speciality in certain skills (Academics, Craft, Performance or Science)\nDice: Intelligence + Blood Sorcery\nDots replace any skill that caster already has but gain an extra die if they already have the speciality. On a total failure, caster takes Aggravated Damage.",
    "depths of nightmare":" Curse someone with nightmares that cause Willpower Damage, which can't be healed during the Ritual's duration.\nDice: Intelligence + Blood Sorcery\nOn a total failure, the victim has pleasant dreams and is pointed towards the caster.",
    "elemental grasp":	"Command your chosen element to interfere with a target	\nDice: Intelligence + Blood Sorcery\nTarget takes Superficial Health Damage and must make an appropriate roll to continue. Caster gains one die to their Ritual pool if the element is already active, like water during a flood.",
    "enhance dyscrasia":"Allow multiple Kindred to feed from one Dyscrasia without destroying it.\nDice: Intelligence + Blood Sorcery\nUsually, they will use Enrich the Blood first.",
    "eyes of babel":"By consuming the eyes and tongue of another, they gain the ability to read and speak any language known by the victim.\nDice: Intelligence + Blood Sorcery\nThis Ritual may incur Stains.",
    "illuminate trail of prey":	"Allows the caster to follow the trail of a specific person.\nDice: Intelligence + Blood Sorcery\nThe victim's face must be known by the caster.",
    "le sang de l'amour":"Create a connection between two people, providing they desire each other at the time the Ritual is cast	\nDice: Intelligence + Blood Sorcery\nBoth participants can use Resolve + Awareness to get an estimation of where the other is. On a total failure of the initial Ritual, this roll disorients them and their Composure is temporarily reduced by one.",
    "soporific touch":"Convert a dose of vitae to weaken their victim against mundane manipulations or mind-altering Disciplines.\nDice: Intelligence + Blood Sorcery\nThe Ritual Roll is made after the victim makes contact and is contested against with Stamina + Resolve.",
    "silentia mortis":"Replicates Silence of Death (Obfuscate ●), which creates a radius of silence\nDice: Intelligence + Blood Sorcery\nIf intended for someone other than the caster, they will also have to make their own Rouse Check.",
    "shroud of silence":"Prevent sounds from escaping a room.\nDice: Intelligence + Blood Sorcery\nRequires vitae from a Kindred who possesses Obfuscate",
    "tiamat glistens":"Attune yourself to a place of power, like a Furcus\nDice: Intelligence + Blood Sorcery\nCaster gains bonuses to Rituals they cast. Only one caster can be attuned to a place of power. If someone else performs the Ritual, the original caster loses their bonus immediately.",
    "truth of blood":"The caster can discern truth from lies.\nDice: Intelligence + Blood Sorcery\n	The target rolls Composure+Occult to resist. This Ritual cannot get past memory wiping Disciplines.",
    "unseen underground":"Become invisible underground.\nDice: Intelligence + Blood Sorcery\nImmediately ends if they go above ground.",
    "viscera garden":"Grow Blood-addicted plants that can consume corpses\nDice: Intelligence + Blood Sorcery\nCan be eaten by Kindred, they do not slake hunger but they stay down. Mortals who ingest a plant are more susceptible to Disciplines.",
    "ward against spirits":"Protect themselves against spirits.\nDice: Intelligence + Blood Sorcery\nUses standard rules for Wards.",
    "warding circle against ghouls":"Protect themselves against Ghouls.\nDice: Intelligence + Blood Sorcery\nUses standard rules for Wards.",
    "web of hunger":"Extension of Extinguish Vitae allows the user to control more than one person's vitae.\nDice: Intelligence + Blood Sorcery\nWithout the dagger, this ritual would be level 4th or 5th level.",
    #LEVEL 3
    "bladed hands":	"Sharpens the user's hands into a weapon.\nDice: Intelligence + Blood Sorcery\nTreated as a light piercing Brawl weapon with a +2 modifier.",
    "bloodless feast":"Purify blood, creating a clear blood-like substance.\nDice: Intelligence + Blood Sorcery\nThose who consume the clear vitae enough are weaker to diablerie.",
    "blood sigil":	"Create a tattoo on a Kindred which also contains a message	\nDice: Intelligence + Blood Sorcery\nCan read the message with a Resolve + Occult roll or by Sense the Unseen (Auspex ●). Caster can remove the Blood Sigil by spending Willpower and touching the tattoo.",
    "communal vigor":"A Pack Priest shares their Blood Potency with their pack.\nDice: Intelligence + Blood Sorcery\nThe Priest gains three bonus dice on Dominate and Presence tests against packmates.",
    "dagon's call":	"The caster can rupture the blood vessels of a victim from afar.\nDice: Roselve+ Blood Sorcery\nThe caster can use this up to two additional times, each costing an additional Rouse Check. The opposing roll is Stamina + Resolve.",
    "Deflection of Wooden Doom":"This ritual protects them from being staked.\nDice: Intelligence + Blood Sorcery\nDo not roll the Ritual Roll until staked.",
    "elemental shelter":"Meld with your chosen element, similar to Earth Meld (Protean ●●●)\nDice: Intelligence + Blood Sorcery\nFire Kolduns must resist terror frenzy before casting this ritual. Koldun's form can be seen with a Wits + Awareness roll or by Sense the Unseen (Auspex ●). If bonded element is removed, such as the fire going out, the Koldun enters torpor.",
    "essence of air":"Allows for flight.\nDice: Intelligence + Blood Sorcery\nThe Camarilla frowns upon this Ritual due to its Masquerade dangers.",
    "eyes of the past":	"See what happened at their current location in the past.\nDice: Intelligence + Blood Sorcery\nIt only holds events within the last five years.",
    "fire in the blood":"Create anguish of fire in one's blood to incapacitate\nDice: Intelligence + Blood Sorcery\nA victim can only be affected by this Ritual once per night.",
    "firewalker":"Allow themselves and their comrades resistant to fire.\nDice: Intelligence + Blood Sorcery\nThis ritual can be performed on others, but the fingertip removal must all come from the caster.",
    "galvanic ruination":"Short out electronics and wiring nearby.\nDice: Intelligence + Blood Sorcery\nGenerally, it only affects the range of a warehouse or three-story building, but can be extended by adding 1 Difficulty per additional building.",
    "gentle mind":"Protect the mind of a target against Frenzy.\nDice: Intelligence + Blood Sorcery\nThe caster must share blood with another and cannot cast it upon themselves.",
    "haunted house":"Make a haven appear as if it's haunted.\nDice: Intelligence + Blood Sorcery\nThe effects last for 10 years.",
    "illusion of peaceful death":"Make a corpse appear as if it'd died a natural death.\nDice: Intelligence + Blood Sorcery\nThe body must have at least half of the body's blood to succeed.",
    "illusion of perfection":"Become a nondescript person to blend into crowds.\nDice: Intelligence + Blood Sorcery\nSimilar to the ability Mask of a Thousand Faces.",
    "nepenthe":"Create a draught that can remove Stains, but prolonged use of it can make those Stains permanent\nDice: Intelligence + Blood Sorcery\nUsing Nepenthe two sessions in a row causes one Stain to become permanent. This is cumulative, e.g. four sessions gives two permanent Stains.",
    "one with the blade":"Claim ownership of a weapon and protect it from damage.\nDice: Intelligence + Blood Sorcery\nOnly one weapon can hold this ritual at a time.",
    "sanguine watcher":	"Create a small rat out of vitae.\nDice: Intelligence + Blood Sorcery\nThe caster can send the rat to go where they instruct to observe or steal, but the instructions must be very explicit.",
    "seeing with the sky's eyes":"Observe a target from above\nDice: Intelligence + Blood Sorcery\nPlayer can ask one question about location and surrounding per success roll. Critical Wins give 3 extra questions and can gain information about Ambitions, Desires, Convictions and Humanity.",
    "seeing with the skys eyes":"Observe a target from above\nDice: Intelligence + Blood Sorcery\nPlayer can ask one question about location and surrounding per success roll. Critical Wins give 3 extra questions and can gain information about Ambitions, Desires, Convictions and Humanity.",
    "seeking tiamat":"Find veins of the Earth\nDice: Intelligence + Blood Sorcery\nCritical wins discover the closest vein and points towards 2 Furcae on that vein.",
    "sleep of judas":"Incapacitate a vampire by drugging them.\nDice: Intelligence + Blood Sorcery\n	Make the Ritual Roll when the target is drugged.",
    "soul of the hemonculus":"Create a Hemonculus, a shrivelled, smaller and weaker version of the caster, who must obey your every command\nDice: Intelligence + Blood Sorcery\nImmune to the sun but cannot be Embraced, made into a ghoul or have a Blood Bond. Vampires slake no Hunger if they drink from it.",
    "stone of the true form":"Dispel illusions and creatures altered via Disciplines and Rituals\nDice: Intelligence + Blood Sorcery\nMust throw the stone with Dexterity + Athletics. The target resists the Ritual with Resolve + Occult. On a win, illusions are dispelled, shapeshifters are painfully returned to their original form and beings made through Disciplines, like a Vozhd, are separated to their original components.",
    "the unseen change":"Lupines entering the area are forced into Wolf Form.\nDice: Intelligence + Blood Sorcery\nIf they do not succeed on the Ritual Roll against a contested Willpower test, they enter in Lupus Form.",
    "trespass":	"Allows the caster to easily sneak around a building, such as by flowing through crevices that blood can fit through\nDice: Intelligence + Blood Sorcery\nUnlike Incorporeal Passage, the caster can be attacked providing they are able to notice the caster.",
    "viral haruspex":"Gather information from everyone in an area suffering from a certain disease\nDice: Intelligence + Blood Sorcery\nCaster must drink from someone with the disease within 24 hours before casting this Ritual.",
    "ward against lupines":"Protects themselves against Werewolves.\nDice: Intelligence + Blood Sorcery\nUses standard rules for Wards.",
    "warding circle against spirits":"Protect themselves against spirits.\nDice: Intelligence + Blood Sorcery\n	Uses standard rules for Wards.",
    #lEVEL 4
    "compel the inanimate":"Give a simple command to an inanimate object which it follows a few minutes later\nDice: Intelligence + Blood Sorcery\nThe caster must remain in the same general area as the object. Sense the Unseen (Auspex ●) can detect the caster with a Wits + Auspex vs. caster's Composure + Blood Sorcery roll.",
    "defense of the sacred haven":"Protect a haven with mystical darkness from the sun.\nDice: Intelligence + Blood Sorcery\nThe Ritual roll is made once the sun rises.",
    "egregore consultation":"By hosting an illness, the caster is able to enhance Skills by access the experiences of everyone with that illness in the area\nDice: Intelligence + Blood Sorcery\nIf a Skill is very common in an area, like Finance in New York, the caster can get extra die to their roll, at a maximum of two.",
    "eyes of the nighthawk":"Take control of a carnivorous bird and act through them.\nDice: Intelligence + Blood Sorcery\nThe user can use most non-physical Disciplines through the bird.",
    "feast of ashes":"Stop another Kindred from drinking blood for one night.\nDice: Intelligence + Blood Sorcery\nThe ritual roll is made against the victim's Resolve + Willpower. The victim can eat the ashes to slake hunger but only down to 3.",
    "guided memory":"With the Blood of another vampire, experience their memories guided by them.\nDice: Intelligence + Blood Sorcery\nThis can be used to unlock Discipline powers, Merits and other gifts.",
    "incorporeal passage":"The caster's form becomes ghost-like.\nDice: Intelligence + Blood Sorcery\nThey may only interact through speech and sight.",
    "innocence of the child's heart":" Put up a blockade against Scry the Soul to hide diablerie and other vampiric traits.\nDice: Intelligence + Blood Sorcery\nThere's no record of Nicolai sharing this ritual with his fellow Tremere and is only learned by capturing his notes or by ST discretion.",
    "innocence of the childs heart":" Put up a blockade against Scry the Soul to hide diablerie and other vampiric traits.\nDice: Intelligence + Blood Sorcery\nThere's no record of Nicolai sharing this ritual with his fellow Tremere and is only learned by capturing his notes or by ST discretion.",
    "innocence of the child heart":" Put up a blockade against Scry the Soul to hide diablerie and other vampiric traits.\nDice: Intelligence + Blood Sorcery\nThere's no record of Nicolai sharing this ritual with his fellow Tremere and is only learned by capturing his notes or by ST discretion.",
    "invisible chains of binding":"Confine a victim to a single spot\nDice: Intelligence + Blood Sorcery\nThe victim is unable to move from that spot for one hour per success in the margin unless the chain is destroyed or removed.",
    "land's sustenance":"Feed from a place of power, turning it into a place of suffering where injuries become more severe.\nDice: Intelligence + Blood Sorcery\nLasts until end of the Story before needing to be renewed. Once per Session, they can automatically pass a number of Rouse Checks equal to their margin on the Ritual roll.",
    "rending the sweet earth":	"Pull a vampire from the earth who is using Earth Meld.\nDice: Intelligence + Blood Sorcery\nThe ritual automatically awakens the other vampire unless they are in torpor or the Ritual Roll is a Critical Win.",
    "riding the earth's vein":"Travel from one furcus to another random one.\nDice: Intelligence + Blood Sorcery\nThe caster has no control over where they end up. This Ritual is one way and only activates where it was first cast.",
    "protean curse":"Transform a target into a bat similar to Metamorphosis.\nDice: Intelligence + Blood Sorcery\nThis cannot be used on the caster.",
    "ward against cainites":"Protects themselves against Kindred.\nDice: Intelligence + Blood Sorcery\nUses standard rules for Wards. A vampire examining this ward may read the name of the caster with an Intelligence + Auspex vs Intelligence + Blood Sorcery roll.",
    "warding circle against lupines":"Protects themselves against Werewolves.\nDice: Intelligence + Blood Sorcery\nUses standard rules for Wards.",
    #LEVEL 5
    "antebrachia ignium":"Set their arms on fire\nDice: Intelligence + Blood Sorcery\nThe user is only resistant to fire on their arms.",
    "dominion":	"Stop the use of Animalism, Auspex, Dominate, and Presence within a building.\nDice: Intelligence + Blood Sorcery\nThe area of effect is determined by the amount of Rouse Checks.",
    "eden's bounty":"Drain blood from nearby creatures\nDice: Intelligence + Blood Sorcery\nFor the remainder of the chapter, mortals suffer 1 die penalty to Physical rolls and take 1 Aggravated health damage.",
    "edens bounty":"Drain blood from nearby creatures\nDice: Intelligence + Blood Sorcery\nFor the remainder of the chapter, mortals suffer 1 die penalty to Physical rolls and take 1 Aggravated health damage.",
    "elemental attack":"The Koldun commands their chosen element to attack a foe. This can be a Chain Ritual\nDice: Intelligence + Blood Sorcery\nIf their element is already active, like Air during a storm, they get an extra die to their Ritual pool. If Chained with Elemental Grasp and Tiamat Glistens, the Ritual becomes a natural disaster, e.g. Tornado, Magma Flow or Tsunami",
    "escape to true sanctuary":"Create a one-way portal.\nDice: Intelligence + Blood Sorcery\nA caster may only have one set of these circles active at a time.",
    "fisher king":"Makes the caster one with their land, giving them access to it's secrets. This can be a Chain Ritual			\nDice: Intelligence + Blood Sorcery\nCan make a Wits + Streetwise or Survival roll to ask questions about the land. The caster can ask one extra question per session. This Ritual lasts until the end of the story. If Chained with Land's Sustenance and Compel the Inanimate, the casters gain complete control over the land and the casters can heal a total of 5 Aggravated damage each night.",
    "heart of stone":"Turns their heart to stone preventing staking. The Caster also suffers from emotional detachment, taking penalties to Remorse or active Social-related rolls.\nDice: Intelligence + Blood Sorcery\nThey are unable to use Presence during this ritual's use but gain a bonus when resisting its use on them.",
    "shaft of belated dissolution":"A stake that will seek out another vampire's heart and will cause final death if it finds it.\nDice: Intelligence + Blood Sorcery\nEven if an attack with this stake fails to hit the heart, if it hits, a splinter will break and move towards the heart to eradicate the victim.",
    "simulacrum gate":"Create a gate to teleport multiple vampires.\nDice: Intelligence + Blood Sorcery\nThere is only one of these known to exist currently.",
    "transferring the soul":"Take over a body from diablerie.\nDice: Intelligence + Blood Sorcery e Intelligence + Oblivion\nPrerequisite:	Another Kindred who knows Oblivion ●●●●●.\nIt is possible to be done by one Kindred who possess level 5 in both powers.",
    "warding circle against cainites":"Protects themselves against Kindred.\nDice: Intelligence + Blood Sorcery\nUses standard rules for Wards.",

    #CELERITY
    "cat's grace":'Automatically pass balance tests. Does not work on objects that cannot support their weight.',
    "cats grace":'Automatically pass balance tests. Does not work on objects that cannot support their weight.',
    'rapid reflexes':'Faster reactions and minor actions. This power also prevents them from taking a penalty when they have no cover during a firefight.',
    "fleetness":"Add Celerity rating for non-combat Dexterity test or defending. This may be used once per turn when defending with associated pools.",
    "rush job":"Perform a Skill-related task that would take a long time in mere seconds. This power does not speed up attacks or defenses.",
    'blink':"Closes the distance as if teleporting.\nDice: Dexterity + Athletics\nThe user moves in a straight line and may need to make checks against difficult terrain.",
    'traversal':"Move fast enough to move up vertical surfaces or liquid surfaces.\nDice: Dexterity + Athletics\nThe Storyteller should inform the user beforehand if the target is too far away",
    'weaving':"Remove the penalty from dodging multiple ranged opponents. The user can all add their Celerity rating to ranged dodging attempts.",
    "blurred momentum":'Attacks against the user with fewer successes than their Celerity rating miss. This works against powers that do not allow defense tests.',
    'draught of elegance':'Turn their vitae into a Celerity boost for others. Each drinker must take one Rouse Checks worth.',
    'unerring aim':'The world slows down to a crawl.\nAmalgam: Auspex ●●\nThose with Celerity 5 may nullify this power with a Rouse Check and defend.',
    'unseen strike':'Disappear then reappear to surprise attack an enemy.\nDice: Dexterity + Celerity vs Wits + Awareness\nAmalgam: Obfuscate ●●●●\nIf the test is won, the attack is treated as a surprise attack. Else it follows the same attack/movement rules as Blink.',
    'lightning strike':"Attack with lightning speed. Those with Celerity 5 may nullify this power with a Rouse Check and defend.",
    "split second":"Alter the events given by Storyteller in a current scene within reason. The action should be reasonable and accomplished within a few seconds in real-time.",

    #DOMINATE
    'cloud memory':"Make someone forget the current moment.\nDice: Charisma + Dominate vs Wits + Resolve'\nNo rolls are needed when the target is an unprepared mortal.",
    'compel':'Issue a single command.\nDice: Charisma + Dominate vs Intelligence + Resolve\nNo rolls are needed when the target is an unprepared mortal. However, mortals who have been Dominated in this scene already or this goes against their nature may roll to resist.',
    'slavish devotion':"Those already underneath Dominate find it easier to resist other kindred's Dominate.\nAmalgam: Fortitude ●\nAttempts by a third party take a dice penalty equal to the other vampire's Fortitude rating.",
    'mesmerize':'Issue complex commands.\nDice: Manipulation + Dominate vs Intelligence + Resolve\nNo rolls are needed when the target is an unprepared mortal. However, if this goes against their nature they may roll to resist.',
    'dementation':'Drive others insane.\nDice: Manipulation + Dominate vs Composure + Intelligence\nAmalgam: Obfuscate ●●\nTo use this power, the user must have had a conversation with them.',
    "domitor's favor":'Make defiance while under a Blood Bond more difficult.Total fail on defiance rolls means the bond does not weaken that month.',
    "domitors favor":'Make defiance while under a Blood Bond more difficult.Total fail on defiance rolls means the bond does not weaken that month.',
    'forgetful mind':"Rewrite someone's memory.\nDice: Manipulation + Dominate vs Intelligence + Resolve\nEach point of margin on the test allows one additional memory to be altered.",
    'submerged directive':"Implant Dominate orders as suggestions for victims.\nPrerequisites: Mesmerize.\nThese orders never expire until completed and targets can only have one at a time.",
    'ancestral dominion':'Urge a descendant to act even if against their own opinion.\nDice: Manipulation + Dominate vs Intelligence + Resolve\nAmalgam: Blood Sorcery ●●\nPrerequisites: Mesmerize.\nFor each generation separating them, the target gains an additional die to resist.',
    'implant suggestion':"Change another's personality or opinion temporarily.\nDice: Manipulation + Dominate vs Composure + Resolve\nAmalgam: Presence ●\nNo test required for unprepared mortals unless it's a change that opposes their core beliefs.",
    'rationalize':"	Convince victims of Dominate it was their idea the entire time. If pressed on their actions the victim can make a test and if successful they question their actions.",
    'tabula rasa':"Erase the victim's memory to the point they don't know who they are.\nDice: Resolve + Dominate vs Composure + Resolve\nFollowing this power's use is generally a string of lies and Path Indoctrination.",
    'mass manipulation':"Extend effects of Dominate to multiple targets. The victims need to see the eyes of the user. The user makes the roll against the strongest of the group.",
    'terminal decree':"	Bolster effects of Dominate to be able to circumvent victims' self-preservation. Terminal commands are always resisted instead of auto failing.",

    #FORTITUDE
    "resilience":"Add their Fortitude rating to the health track.",
    "unswayable":"Mind	Add Fortitude rating to rolls to resist methods to sway the character's mind against their will including supernatural.",
    "earth's perseverance":"Become impossible to move from that spot. While they cannot be moved, they can still be harmed and so can the floor beneath them.",
    "earths perseverance":"Become impossible to move from that spot. While they cannot be moved, they can still be harmed and so can the floor beneath them.",
    "enduring beasts":"Share the vampire's toughness with animals.\nDice: Stamina + Animalism\nAmalgam:	Animalism ●\nIf used on their Famulus, it is free and automatic without a roll required.",
    "invigorating vitae":"Heal mortals faster with the Blood.\nAmalgam: Auspex ●\n The risk of ghouling or blood bonding remains present.",
    "obdurate":	"Maintain footing when hit with a massive force.\nDice: Wits + Survival\nAmalgam: Potence ●●\nAny superficial damage from falling or being hit is reduced by the Fortitude score, before being halved.",
    "toughness":"Subtract the Fortitude rating from all superficial damage taken before halving, it cannot be rounded down below one. This occurs before halving the damage but cannot reduce it below one.",
    "defy bane":"Convert Aggravated Damage to Superficial Damage.\nDice: Wits + Survival\n	They may not heal the superficial damage for the rest of the scene.",
    "fortify the inner façade":	"Increasing the Difficulty of mental powers to read or pierce the mind by half of the Fortitude Rating. If the rules allow them to resist, they add their Fortitude rating to their pool instead.",
    "seal the beast's maw":	"A vampire can ignore the effects of hunger if they do not increase hunger from the two Rouse Checks, but reduce their dice pools. If a dice pool reduces to 0, a Fury Frenzy test is made.",
   "seal the beasts maw":	"A vampire can ignore the effects of hunger if they do not increase hunger from the two Rouse Checks, but reduce their dice pools. If a dice pool reduces to 0, a Fury Frenzy test is made.",    
    "valeren":"Mend an injured vampire.\nDice: Intelligence + Fortitude\nAmalgam: Auspex ●\nA subject can be affected by the power only once a night.",
    'draught of endurance':"Turn their vitae into a Fortitude boost for others. Each drinker must take one Rouse Checks worth.",
    "gorgon's Scales":"Resonances give the Kindred different bonuses. Choleric frees vampires from being staked, Melancholy reduces fire damage, Phlegmatic strengthens against Auspex and, Sanguine reduces damage from sunlight.",
    "shatter":"The opponent takes the damage which Toughness subtracts.\nPrerequisite: Toughness\nWeapons will break if their modifier is met in damage received.",
    "flesh of marble":"	Ignore the first source of physical damage each turn unless sunlight. A critical win on an attack bypasses this power.",
    "prowess from pain":"No longer suffers penalty from Health damage and can increase one Attribute per level of damage on their tracker. The Attributes may not exceed their Blood Surge value + 6.",

    #OBFUSCATE
    'cloak of shadows':'As long as the user stands still they blend into their surroundings.',
    'silence of death':"Nullifies the sounds a user makes. This power does not eliminate powers made outside of the user's personal space.",
    "chimerstry":"Create brief but realistic hallucinations.\nDice: Manipulation + Obfuscate vs Composure + Wits\nAmalgam: Presence ●\nThis can be used in combat but can only affect targets once per conflict.",
    "ghost's passing":"The user can bestow Obfuscate onto an animal.\nAmalgam: Animalism ●\nSense the Unseen can discern signs as per general Obfuscate rules",
    "unseen passage":"The user can now move while remaining hidden. This power will fail if the user is being actively watched when activated.",
    "ventriloquism":"Throw their voice so only the intended recipient can hear it.\nDice: Wits + Obfuscate vs Resolve + Composure\nAmalgam: Auspex ●●\nCan be used on anyone in line of sight.",
    "doubletalk":"Say one thing but convey something else in secret.\nDice: Composure + Obfuscate vs Wits + Auspex\nAmalgam: 	Auspex ●.Others present can contest.",
    "fata morgana":	"Elaborate hallucinations.\nDice: Manipulation + Obfuscate\Amalgam: Presence ●●\nIf the hallucination can trigger Frenzy, give the test at 1 diff lower than the real thing.",
    "ghost in the machine":	"Allows the effects of Obfuscate to be transmitted through technology when viewed on a live screen. 	If viewed later the image seems blurred, making identification harder.",
    "mask of a thousand faces":	"Make themselves appear as a mundane face rather than disappear allowing interaction and communication. This power allows them to interact and speak to others around them.",
    "mask of isolation":"Force Mask of a Thousand Faces onto a victim.\nDice: Manipulation + Obfuscate vs Charisma + Insight\nAmalgam: Dominate ●\nPrerequisite: Mask of a Thousand Faces\nShould the user be made aware of the power being used on them the effects end.",
    "mental maze":"Remove all sense of direction and location from a victim in a location.\nDice: Charisma + Obfuscate vs Wits + Resolve\nAmalgam: Dominate ●\nEye contact is required to active the power.",
    "mind masque":"Hide and replace emotions and thoughts against those who wish to read them, be it through mundane or supernatural means.\nDice: Intelligence + Obfuscate\nAmalgam: Dominate ●\nThe difficulty to mask their emotion depends on how complicated they want the ruse to be.",
    'conceal':	"Cloak an inanimate object.\nDice: Intelligence +Obfuscate\nAmalgam: Auspex ●●●\nThis power cannot affect anything larger than a two-story house or anything moving on it's own.",
    'vanish':"Activate Cloak of Shadows or Unseen Passage while being observed.\nDice: Wits + Obfuscate vs Wits + Awareness\nThis power makes the memory of the Kindred foggy and indistinct, but it will not affect the memories of vampires.",
    "cloak the gathering":"Shelter companions under Obfuscate. This power extends to a number of people equal to the user's Wits, plus additional Rouse Checks.",
    "imposter's guise":	"Appear as someone else.\nDice: Wits + Obfuscate vs Manipulation + Performance\nPrerequisite: Mask of a Thousand Faces\nThe face they wish to copy must be studied for at least five minutes from multiple angles.",
    "imposters guise":"Appear as someone else.\nDice: Wits + Obfuscate vs Manipulation + Performance\nPrerequisite: Mask of a Thousand Faces\nThe face they wish to copy must be studied for at least five minutes from multiple angles.",    

    #OBLIVION
    "ashes to ashes":"Destroy a corpse by dissolving it.\nDice: Stamina + Oblivion vs Stamina + Medicine/Fortitude\nIf the body is not animated it will dissolve throughout three turns with no test needed.",
    "binding fetter":"Allow users to be able to identify a fetter by use of their senses.\nDice: Wits + Oblivion\n	During its use the user receives a -2 penalty to all Awareness, Wits, and Resolve rolls.",
    "oblivion sight":"See in darkness clearly and see ghosts present. While in use there is a two-dice penalty to social interactions with mortals.",
    "shadow cloak":	"+2 bonus to stealth rolls and intimidation against mortals.",
    "arms of ahriman":	"Conjures shadow appendages that the user can control but the user is unable to do anything else.\nDice: Wit + Oblivion\nAmalgam: Potence ●●\nArms do not have a health tracker and do not require Composure + Resolve to escape.",
    "fatal prediction":	"Increase the chances of a mortal being harmed by exterior forces. \nDice: Resolve + Oblivion vs Wits + Occult\nAmalgam: Auspex ●●\nFor every success over margin the victim takes 1 Aggravated damage throughout the duration. The vampire cannot interact with the victim directly or indirectly. This is an updated version of Fatal Precognition.",
    "fatal precognition":"Vision of a non-vampires death.\nDice: Resolve + Oblivion\nAmalgam: Auspex ●●\n	The vampire must be able to see or hear the target during the power's use.",
    "shadow cast":	"Conjure shadows from the user's body. The shadow can be extended up to twice the user's Oblivion rating in yards/meters. Those standing in the shadow take more Willpower damage from social conflict.",
    "where the veil thins":	"Determine the density of the Shroud in their area.\nDice: Intelligence + Oblivion\nThe book lists a chart stating the possible different densities and causes, as well as their effects.",
    "aura of decay":"Harnessing their connection to Oblivion can make plants wilt, animals and humans sick, and food spoil.\nDice: Stamina + Oblivion vs Stamina + Medicine/Fortitude\nAll social rolls the vampire makes when this power is active takes a two dice penalty. Any contaminated food eaten gives two Superficial Damage.",
    "passion feast":"Allows a vampire to slake Hunger on the passion of wraiths.\nDice: Resolve + Oblivion vs Resolve + Composure\nAmalgam: Fortitude ●●\nThe hunger consumed does not return the following night.",
    "shadow perspective":"Projects their senses into a shadow within line of sight. The use of this power is undetectable in the shadow other than by supernatural means such as Sense the Unseen.",
    "shadow servant":"Use a shadow to spy on or scare others\nAmalgam: Auspex ●\nThe servant has no mind of its own and cannot endure bright lights able to be destroyed by them.",
    "touch of oblivion":"Wither's a body part on touch. Inflicting such damage may warrant Stains up to Storyteller discretion. The user must grip the target.",
    "necrotic plague":"Manifest illness in victims.\nDice: Intelligence + Oblivion vs Stamina + Medicine/Fortitude\nThis illness cannot be treated in a medical setting as it's supernaturally inflicted, instead only healed by drinking vitae. There is no outcome on Total Failures.",
    "stygian shroud":"Darkness spews out of a nearby shadow and covers the area. The shadow can be extended up to twice the user's Oblivion rating in yards/meters.",
    "umbrous clutch":"Using the victim's shadow they create a portal, dropping them into the user's arms.\nDice: Wits + Oblivion vs Dexterity + Wits\nAn unprepared mortal will be terrified while a vampire must test for fury or fear Frenzy test at a Difficulty 4.",
    "shadow step":	"The user can step into one shadow and appear in another within their sight. 	A willing person may be taken through the Shadow Step but should the user stain, so does the passenger.",
    "skuld fulfilled":	"Reintroduce illnesses someone has recovered from.\nDice: Stamina + Oblivion vs Stamina + Stamina/Fortitude\nIf the victim is a ghoul their immunity to aging is removed and eliminates any vitae in their system.",
    "tenebrous avatar":	"Changes their body into a shadow able to move over any surface or through small spaces. The user takes no damage except sunlight and fire while in this form.",
    "withering spirit":	"Erode a victim's spirit till they are a husk.\nDice: Resolve + Oblivion vs Resolve + Occult/Fortitude\nIf the target is Impaired, they will not return as a wraith.",

    #OBLIVION CEREMONIES
    "gift of false life":"Raise either a single corpse or a group to perform simple single or repetitive tasks.\nDice: Resolve + Oblivion\n\nPrerequisite: Ashes to Ashes\nCorpses are mindless creatures and do not defend themselves from attacks, decaying as normal for the duration of the ceremony.",
    "knowing stone":"Identify the locations of specific ghosts.\nDice: Resolve + Oblivion\nThey must know the ghost's name.","summon spirit":"Summon a spirit from the underworld.\nDice: Resolve + Oblivion\nPrerequisite: Binding Fetter\nThe wraith will disappear at the end of the scene unless a ceremony is used to keep them there such as Compel Spirit.",
    "traveler's call":"Summon another Shalimite.\nDice: Resolve + Oblivion\nPrerequisite: Oblivion Sight\nThe victim can choose to ignore it, taking -2 to all pools in relation to concentration for one scene.",
    "travelers call":"Summon another Shalimite.\nDice: Resolve + Oblivion\nPrerequisite: Oblivion Sight\nThe victim can choose to ignore it, taking -2 to all pools in relation to concentration for one scene.",
    "awaken the homuncular servant":"Create spies and stalkers out of body parts or small animals.\nDice: Resolve + Oblivion\nPrerequisite: Where the Shroud Thins\nThe servant can scale or hop walls and hide, but it cannot speak. It is only able to telepathically communicate single images to its creator.",
    "blinding the alloy eye":"Cameras cannot perceive the user clearly.\nDice: Resolve + Oblivion\nPrerequisite:Shadow Cast\nDo not make the ritual roll until the effect is active.",
    "compel spirit":"Bend a wraith to a vampire's will.\nDice: Resolve + Oblivion\nPrerequisite: Where the Shroud Thins\nThe ritual roll is made against the wraith's Resolve + Composure or Willpower.",
    "maw of ahriman":"Open a portal to the abyss, usually within their mouth.\nDice: Resolve + Oblivion\nThe user cannot speak till it is either cancelled or the next sunrise.",
    "fortezza sindonica":"Create a barrier that harms wraiths.\nDice: Resolve + Oblivion\nPrerequisite: Where the Shroud Thins\nDo not make the Ritual Roll until a wraith attempts to pass.",
    "harrowhaunt":"Keep unwanted visitors from their haven.\nDice: Resolve + Oblivion\nPrerequisite: Aura of Decay\nVampires are able to enter making a fear Frenzy check each turn while inside.",
    "host spirit":	"Allows the user to open their body to a ghost for possession.\nDice: Resolve + Oblivion\nPrerequisite: Aura of Decay\nAlongside the bonus of +2 to Physical Attribute rolls and +2 health, the wraiths Skills can be substituted for the vampire's own at Storyteller discretion.",
    "knit the veil":"Turn a shroud impenetrable.\nDice: Resolve + Oblivion\nPrerequisite: Where the Shroud Thins\nWhen not disturbed this effect does not change for as many nights as the user's Oblivion rating.",
    "name of the father":"Strike a victim's mind with the empty void of Oblivion, leaving them paralyzed.\nDice: Resolve + Oblivion\nPrerequisite:	Shadow Perspective\nThe victim can spend willpower equal to the number of turns they would remain paralyzed to free themselves.",
    "shambling hordes":	"Raise a group of aggressive walking dead.\nDice: Resolve + Oblivion\nPrerequisite:	Aura of Decay\nIf left without commands, they attack anyone around them other than their master.",
    "befoul vessel":" Turn a mortal's blood into poison for other vampires.\nDice: Resolve + Oblivion\nPrerequisite: Necrotic Plague\nThis power leaves no trace other than the mortal dying the next night with the smell of mildew and sweat.",
    "bind the spirit":	"Bind a wraith to a specific location or person.\nDice: Resolve + Oblivion\nPrerequisite: Necrotic Plague\nBound wraiths have the same powers as spectres.",
    "death rattle":	"Inflict the sensory experience of a wraith's death onto a target.\nDice: Resolve + Oblivion\nPrerequisite:	Fatal Precognition\nThe victim contests the ritual roll with Composure + Resolve.",
    "split the veil":"Create a tear into a shroud to allow wraiths to enter.\nDice: Resolve + Oblivion\nPrerequisite: Necrotic Plague\nThis Ceremony reduces the density of the veil and can reduce it to absent, allowing wraiths to come through. The veil increased to frayed after the session ends, stopping any more wraiths.",
    "ex nihilo":"Enter the Shadowlands \nDice: Resolve + Oblivion\nPrerequisite: Withering Spirit\nThe Shadowlands have several rules that do not exist in the world of the living.",
    "lazarene blessing":"Bring a fresh corpse back to life\nDice: Resolve + Oblivion\nPrerequisite: Skuld Fulfilled\nThis lasts until the body dies again or the wraith is exorcised from the host.",
    "pit of contemplation":	"Cast an enemy into Oblivion itself.\nDice: Resolve + Oblivion\nPrerequisite: Tenebrous Avatar\nMortals sucked in are instantly killed.",
    "ashen relic":"Preservation of a Kindred's body.\nDice: Resolve + Oblivion\nThree successes in the margin preserves more.",
    "wisdom of the dead":"Gain information from a corpse skull or head.\nDice: Resolve + Oblivion\nPrerequisite: Ashes to Ashes or Oblivion's Sight.\nAdd two dice to their dice pool if they are still carrying the skull/head for the rest of the night.",

    #POTENCE
    'lethal body':'Unarmed attacks do Aggravated Health damage to mortals when used and ignore one level of armor per Potence rating of user.',
    'soaring leap':'Leap higher and further than usual. They can move as many meters as three times their Potence rating.',
    'prowess':'Add Potence rating to their unarmed damage and to feats of Strength, add half their Potence rating (Rounded up) to Melee damage.',
    'relentless grasp':'Gain supernatural grip strength. Does not benefit the initial grapple test.',
    'brutal feed':"Turn feeding into a violent and messy affair that only lasts seconds to Slake the user's Hunger.",
    'spark of rage':"Strengthens their grip on most surfaces, allowing them to climb or hang unsupported.\nAmalgam: Presence ●●●.\nAgainst vampires, the user will roll Manipulation + Potence vs Intelligence + Composure.",
    'uncanny grip':"Strengthens their grip on most surfaces, allowing them to climb or hang unsupported. The use of this power leaves obvious traces from the damage caused.",
    'wrecker':"Double Potence rating when used for feats of strength.\nPrerequisite: Prowess.\n It cannot be used against living targets.",
    'draught of might':' Might	Turn their vitae into a Potence boost for others. Each drinker must take one Rouse Checks worth.',
    'crash down':'Deal damage to a small area when using Soaring Leap.\nPrerequisite: Soaring Leap.\nDice:Strength + Potence vs Dexterity + Athletics.\nIf opponents total fail or take 3 or more levels of damage they are knocked down.',
    'earth shock':'Inflict Aggravated Health damage to mortals and supernatural creatures alike. This can only be used once per scene.',
    'subtle hammer':"Project the vampire's power in a specific body part. 	You cannot make another attack in the same move, but body parts that have limited movement receive a four-dice bonus or more.",
    'fist of caine':"Inflict Aggravated Health damage to mortals and supernatural creatures alike.",
    
    #PRESENCE
    'awe':'Add Presence rating to any Skill roll involving Persuasion, Performance, or Charisma related rolls as per ST discretion. Once the power wears off the victim reverts to their original opinions.',
    'daunt':'Add Presence rating to any intimidation rolls. Awe and Daunt cannot be used at the same time.',
    'eyes of the serpent':'Immobilize a victim by making eye contact.\nDice: Charisma + Presence vs Wits + Composure\nAmalgam: Protean ●\nA vampire victim can break this by spending Willpower any turn after the first.',
    'lingering kiss':'Usable during feedings, the victim gains a bonus to Social attribute for one night. A withdrawal follows where the victim takes a penalty equal to the original bonus when not actively working towards the next fix. It cannot be used on those under a Blood Bond. Unbondable cannot take this discipline power.',
    'melpominee':'Use Presence without seeing the target, only having them within earshot. This works with Awe, Daunt, Dread Gaze, Entrance, and Majesty.',
    'clear the field':'	Clear a space in a calm and orderly manner.\nDice: Composure + Presence\nAmalgam: Dominate ●●●\nOpposed individually with Wits + Composure',
    'dread gaze':'Instill fear into a target to make them flee.\nDice: Charisma + Presence vs Composure + Resolve\nA critical win against a vampire victim means the victim makes a terror Frenzy at difficulty 3.',
    'entrancement':'Influence someone into a star-struck or beguiled state of mind where they do their best to keep the user happy. Adding their Presence rating in dice to any social rolls against the victim.\nDice: Charisma + Presence vs Composure + Wits\nIf the request is harmful to the victim or their loved ones, or opposes their tenets the test must be made again or Entrancement fails.',
    'thrown voice':'Throw their voice from any point within sight and leave the voice there.\nAmalgam: Auspex ●●●\nA roll is only needed if being used in combination with Irresistible Voice, Melpominee or similar powers.',
    "true love's face": 'The victim will perceive the user as a mortal they have strong emotional ties with, be it hatred or love\nDice: Manipulation + Presence vs Composure + Wits\nAmalgam: Obfuscate ●●●\nCan net stains for the victim if the perceived target is their touchstone.',
    "true love face": 'The victim will perceive the user as a mortal they have strong emotional ties with, be it hatred or love\nDice: Manipulation + Presence vs Composure + Wits\nAmalgam: Obfuscate ●●●\nCan net stains for the victim if the perceived target is their touchstone.',
    "true loves face": 'The victim will perceive the user as a mortal they have strong emotional ties with, be it hatred or love\nDice: Manipulation + Presence vs Composure + Wits\nAmalgam: Obfuscate ●●●\nCan net stains for the victim if the perceived target is their touchstone.',
    'irresistible voice':"The user's voice alone is enough to use Dominate on a target.\nAmalgam: Dominate ●\nDoes not work through technology.",
    'magnum opus':'Infusing Presence into artwork.\nDice: Charisma/Manipulation + Craft\nAmalgam: Auspex ●●●\nAudiences must roll Composure + Resolve to resist its effects.',
    'suffuse the edifice':'Extend Presence onto a building. If the vampire is present they become the focus instead of the building.',
    'summon':"Call someone to them who has had certain Presence powers used on them or tasted the user's vitae.\nDice:	Manipulation + Presence vs Composure + Intelligence\nThe victim will not physically or financially harm themselves to reach the user.",
    "wingman":"Extend Presence onto another character to use. The same Presence power used by both does not double the bonus.",    
    'majesty':"Everyone who looks at the user is dumbstruck unable to act in any way other than self-preservation.\nDice: Charisma + Presence vs Composure + Resolve\nA win on the contested roll allows one turn plus one per margin of freedom.",
    'star magnetism':"Allows the use of presence through live-feed technology, does not work on recorded content. 	If using Entrancement the user must speak the targets name clearly.",

    #PROTEAN
    "eyes of the beast":"Allows the user to see in total darkness. +2 bonus dice to intimidation against mortals when active.",
    "weight of the feather":"The user can make themselves almost weightless.\nDice: Wits + Survival\nDices is only used when activated as a reaction.",
    "feral weapons":" Elongate the user's nails into claws, gaining a +2 modifier to damage or elongate their fangs and not suffer a called shot penalty. Superficial damage inflicted by the user is not halved while active.",
    "vicissitude": "Sculpt the flesh of bodies allowing changes to their own bodies.\nDice: Resolve + Protean\Amalgam: Dominate ●●\nEach success on the roll allows a single change to be made.",
    "serpent's kiss": "When biting someone, inject their own vitae into them. This can also be used to transport powers like Scorpion's Touch.",
    "serpents kiss":"When biting someone, inject their own vitae into them. This can also be used to transport powers like Scorpion's Touch.",
    "serpent kiss":"When biting someone, inject their own vitae into them. This can also be used to transport powers like Scorpion's Touch.",
    "the false sip":"Prevent any blood or Blood from entering their system.\nAmalgam: Fortitude ●\nThey must vomit it back up within the scene or extend to an additional scene by making another Rouse Check.",
    "earth meld":"Sink into the earth and become one with the soil. This power only works on natural surfaces and not artificial such as concrete.",
    "fleshcrafting":"Extends the mastery over the flesh to be used on others.\nDice:Resolve + Protean vs Stamina + Resolve\nAmalgam: Dominate ●●\nPrerequisite: Vicissitude\nAn unwilling subject may resist with the margin of the user's role counting as the number of changes able to be made.",
    "shapechange":"Change into an animal with a similar body mass. Users gain the Physical Attributes and other traits of the animal they've changed into.",
    "visceral absorption":"Draw in the remains of blood and body to the vampire to clean a scene.\nDice: Strength + Protean\nAmalgam: Blood Sorcery ●●\nHunger can be reduced by one per body, up to the level of their Blood Sorcery rating but cannot reduce to 0.",
    "horrid form":"Take on a monstrous shape.\nAmalgam: Vicissitude\nPrerequiste: Dominate ●●\n	Grants several changes equal to the user's Protean rating. Any critical scores are counted as messy criticals and Frenzy checks are made with +2 Difficulty.",
    "metamorphosis":"Extends shape change to be able to change into a larger animal than the vampire's mass.\nPrerequiste: Shapechange\nSame rules as Shapechange.",
    "the heart of darkness":"Allows a vampire to remove their own heart and store it outside of their body.\nAmalgam: Fortitude ●●\nIf the heart is dealt aggravated damage equal to or greater than the user's health tracker, they fall into torpor. It can only be destroyed through fire or sunlight.",
    "mist form":"Turn into a cloud of mist. This power takes three turns to use and may be sped up with additional Rouse Checks on a one-for-one trade.",
    "one with the land":"Sink into the earth of their Domain.\nAmalgam: Animalism ●●\nPrerequisite: Earth Meld\nSame system as Earth Meld however they are not limited by the material.",
    "the unfettered heart":"The heart of the vampire can move freely within the chest, making staking more difficult. Only upon a critical win does the stake penetrate when in melee combat.",

    #THIN BLOOD ALCHEMY
    "body paint":"Create tattoos with personal touches beyond regular tattoos\nCholeric\n\nDice: Dexterity + Craft\nAfter a week, the roll to alter the tattoo is Stamina + Resolve",
    "checkout time":"Enter a deep torpor where there is no difference between you or a corpse\nPhlegmatic\nComing out of this Torpor does not require a Rouse Check. In this state, they have no aura, require no rouse checks and take no damage from sunlight or other banes.",
    "elevate":"Get high regardless of Humanity or Blush of Life. Temporarily enhances Dexterity if well made\nSanguine\nDice: Stamina+Alchemy\nBadly made Elevate still feels great but degrades Dexterity",
    "far reach":"Push, pull, hold or grab objects or people with their mind.\nCholeric\nDice: Resolve +Alchemy vs Strength +Athletics\nKeeping something held in the air requires a check each turn of Resolve + Alchemy Difficulty 3.",
    "food stain":"Mark someone so anyone who drinks from them becomes obvious to the alchemist when they encounter them\nMelancholic\nIf the alchemist has Auspex 2, they become aware as soon as the feeding occurs",
    "gaoler's bane":"Receive a 2-dice bonus when freeing themselves from physical restraints or grapples.\nSanguine.",
    "gaolers bane":"Receive a 2-dice bonus when freeing themselves from physical restraints or grapples.\nSanguine.",
    "gaoler bane":"Receive a 2-dice bonus when freeing themselves from physical restraints or grapples.\nSanguine.",
    "haze":	"Create a mist that follows the user, making it harder to shoot them or identify them.\nPhlegmatic\nThis can be extended to encompass up to five people with an additional Rouse Check.",
    "mercurian tongue":	"Speak other languages than their own. The alchemist can spend Willpower and feed from another person to swap the language the alchemist currently knows.",
    "plug in":"Produce low-level electrical current from their body.\nSanguine\nDice: Resolve +Alchemy\nIt powers through touch and will stop if the connection is lost.",
    "portable shade":"Withstand the effects of Sunlight and walk in the sun.\nSanguine\nDice: Stamina+Alchemy\nThis formula was developed by the Path of the Sun Thin-bloods.",
    "speak from the heart":	"Place a message into someone's blood. The next vampire to drink from them gets the message\nMelancholic\nDifferent drinks used in the creation affect the message",

    "advanced torpor":	"Immediately cause Torpor\nCholeric, Phlegmatic\nAlways heal as a vampire, regardless of flaws. Unlike regular torpor, the vampire always has a Rouse Check re-roll",
    "blacklight surprise":	"Makes UV light damage vampires\nSanguine, Choleric\nKindred who already take damage from UV light, take an extra point",
    "blood of mandagloire":	"Infect the blood of a herd to cause those who feed from it to fall into a dreamless sleep.\nMelancholic\nThin-bloods develop this formula within the Second Inquisition.",
    "blue state":"Forces a target to contemplate obsessively over an ally's failure\nMelancholic, Phlegmatic\nKindred gain stains if an ally violates their convictions. Mortals just hold a grudge",
    "envelop":	"Create a mist that clings to a victim.\nMelancholic, Phlegmatic\nDice: Wits +Alchemy vs Stamina +Survival\nThis can only be employed on single targets one at a time.",
    "friends list":	"See connections between Kindred and mortals\nPhlegmatic\nDice: Intelligence +Alchemy\nStronger connections require fewer and fewer successes.",
    "mirror of trust":"Gain 3 extra dice to persuade or intimidate someone into being honest.\nSanguine\nThin-bloods develop this formula within the Second Inquisition.",
    "red's flaming hot sauce":"Create a supernatural molotov cocktail\nCholeric\nFire spreading from it can be extinguished, but the supernatural source cannot.",
    "reds flaming hot sauce":"Create a supernatural molotov cocktail\nCholeric\nFire spreading from it can be extinguished, but the supernatural source cannot.",
    "red flaming hot sauce":"Create a supernatural molotov cocktail\nCholeric\nFire spreading from it can be extinguished, but the supernatural source cannot.",
    "counterfeit discipline":	"Counterfeit a Discipline, except lv 5 disciplines\nDice: The same as the power channeled.",

    "chemically Induced flashback":	"Imbue and experience a Memorium of another vampire.\nMust use the Fixatio method.\nThe Thin-bloods develop this formula within the Ashfinders.",
    "concoct ashe":	"Create Ashe from the remains of a vampire.\nDice: Intelligence + Alchemy\nMust use the Fixatio method.\nThe Thin-bloods develop this formula within the Ashfinders.",
    "diamond skin":	"Reduces physical damage to the alchemist, turning Aggravated to Superficial\nMelancholic\nDoes not affect fire, acid, sunlight or sorcery",
    "defractionate":"Turn preserved blood into something palatable by any kindred.\nMelancholic, Sanguine\nEach Distillation style has a unique method of tapping for this elixir.",
    "fang stinger":"Introduce blood into a mortal that causes no harm to them but harms vampire's that feed from them.\nDice: Resolve +Alchemy vs	Stamina +Resolve\nThin-bloods develop this formula within the Second Inquisition.",
    "fireskin":	"Superheat your body. They gain +1 additional fire damage with strikes with their body. They are immune to fire but cold hurts more",
    "freezer fluid":"Freeze a vampire's body.\nMelancholic, Phlegmatic\nDice: Resolve + Alchemy vs Stamina +Resolve\nThin-bloods develop this formula within the Second Inquisition.",
    "hospital chains":	"Prevent someone from healing\nPhlegmatic\nDice: Distillation roll vs Stamina\nCritical wins last 2 days per success",
    "mandagloire":"	Emit a gas that causes rigid paralysis in mortals and supernatural creatures.\nPhlegmatic\nDice: Stamina + Alchemy vs Stamina + Resolve\nFor Fixatio alchemists this can be slipped into a drink or burned.",
    "martian purity":"Expel blood-borne illnesses through ignited gases\nCholeric\nDeals 2 Aggravated Health damage",
    "mask off":	"Creates an explosion of gas that causes no damage but negates the Blush of Life\nCholeric, Melancholic\nDice: Stamina + Resolve\nThose affected cannot use Blush of Life for rest of the night. The opposing pool is rolled against the Distillation pool",
    "on demand sunburn":"Become a sun battery and harm vampires they touch.\nCholeric\nThis formula was developed by the Path of the Sun Thin-bloods.",
    "profane hieros gamos":	"Change their form into their ideal human shape.\nMelancholic, Phlegmatic\nDice: Stamina +Resolve\nThis cannot spare the Nosferatu from their bane.",
    "rumor":"Make a statement and convince one person to agree.\nPhlegmatic\nDice: Manipulation + Alchemy vs Wits + Awareness\nIt lingers till something contradicts the target's agreement.",
    "stay the falling sand":"Slow time\nMelancholic\nDice: Resolve + Alchemy\nCannot be used on living creatures or kindred.",
    "tank":	"Strengthen their resistance to damage\nCholeric\nThe first damage they take is reduced by five.",
    "tlc":	"Enhances the blood of animals so it slakes the same as mortal blood\nAnimal,Choleric\nKilling an animal cannot slake Hunger to zero",
    "troll the pious":"Cause negatives effects to the religious\nMelancholic\nGives one-dice penalty to most dice pools. Those with True Faith take a two-dice penalty instead and suffer hallucinations",
    "airborne momentum":"Achieve flight\nCholeric, Sanguine\nDice: Strength + Alchemy vs Strength +Athletics (if resisted)\nCan move at running speed and carrying a human-sized mass slows to walking speed. This can only be used by the alchemist.",
    "copycat":"Turn into an approximate copy of someone\nCholeric, Phlegmatic\nDice: Intelligence + Awareness\nThose who know the person whose appearance is borrowed can recognise the difference by rolling the Opposing pool against the Distillation roll",
    "discipline channeling":"Imbue Ashe with Disciplines\nMust use the Fixatio method.\nThe Thin-bloods develop this formula within the Ashfinders.",
    "half living conductor":"Be immune to, and redirect electrical currents\nCholeric, Sanguine\nDice: Stamina + Alchemy\nUsing electricity to attack requires Dexterity + Alchemy. Deals 2 damage, Aggravated to mortals, Superficial to vampires.",
    "hollow leg":"Poison another Kindred so that they are unable to slake hunger.\nNon-Resonant Human Blood\nDice: Intelligence + Alchemy vs Stamina + Composure\nThe victim must be tricked, coerced or forced into drinking this.",
    "red state":"Erases memories of someone's misdeeds\nSanguine, Phlegmatic\nBeing told of the crime makes no sense to the target",
    "short circuit":"Overload the batteries in electronics or electrical equipment.\nMelancholic\nThis allows for alchemists to touch either the object itself or metal connected and short it out.",
    "toxic personality":"Secrete caustic bile from their pores and orifices.\nCholeric\nDice: Strength/Dexterity + Alchemy vs Dexterity +Alchemy\nThe alchemist may touch this without being harmed. It can either be used as a physical attack or by making another Rouse Check, spit as a ranged attack.",
    "vitae msg":"Make it hard for vampires to resist feeding off someone.\nSanguine\nVentrue feeding off someone appointed with this require 1 less Willpower if they aren't in their preferred category.",
    "awaken the sleeper":"Awaken a vampire from torpor\nCholeric or Sanguine\nEach Distillation style has a unique method of tapping for this elixir.",
    "flowering amaranth":"Share diablerie with other thin-bloods.\nDice: Resolve + Alchemy vs Willpower + Blood Potency\nUpon a win they gain a Discipline as if a full-blooded though they cannot level it, they do no gain generation and still lose 1 Humanity. They also gain the black-veined aura of Diablerie.",
    "oment of clarity":"Harness the power of the Beast to support them.\nPhlegmatic\nAdd four dice to Mental Skill pools, Discipline Skill pools, and to Mental resistance checks when Disciplines are used on them. Immune to Messy Criticals and Frenzy.",
    "saturn's flux":"Break Blood-bonds\nPhlegmatic\nRemoving the Blood-bond is painful but Mortals take no damage. Kindred have to take Aggravated damage to expel.",
    "saturns flux":"Break Blood-bonds\nPhlegmatic\nRemoving the Blood-bond is painful but Mortals take no damage. Kindred have to take Aggravated damage to expel.",
    "saturn flux":"Break Blood-bonds\nPhlegmatic\nRemoving the Blood-bond is painful but Mortals take no damage. Kindred have to take Aggravated damage to expel."
}