easter_eggs_test = {
    'vampiro':'Nós não usamos a palavra "Vampiro"! O que você é, um animal? Não, você é um Kindred, um Membro. Modere o linguajar!',
    'camarilla':"Camarilla? A Camarilla não existe mais! 2022 foi o último ano que ela existiu em Porto Alegre. Sabe por quê? Então, me conta, eu também queria saber. Dizem que os magos erram a mão em um de seus encantos e algo aconteceu. Você sabe de alguma coisa?",
    'anarquia':"Dizem que ela existe, que ela ronda os humanos como uma mão amiga, um ombro para se chorar, uma imagem para adorar.Mas como todo movimento juvenil, talvez ela tenha morrido no esquecimento. Dizimada pelos próprios pecados.",
    'poabynight':'Quer saber mais? www.poabynight.com.br!',
    'disciplinas':'Quer saber mais sobre as disciplinas? Coloca o nome delas em inglês aqui no chat que você vai receber a mesma informaçõe que há no vtm.paradoxwikis.com',

    "predator type roll" :"Alleycat - Strength + Brawl is to take blood by force or threat. Wits + Streetwise can be used to find criminals as if a vigilante figure.\n\nBagger - Intelligence + Streetwise can be used to find, gain access and purchase the goods.\n\nBlood Leech - This Predator Type is suggested to not be abstracted down to a dice pool.\n\nCleaver - Manipulation + Subterfuge is used to condition the victims, socializing with them and feeding from them without the cover being blown.\n\nConsensualist - Manipulation + Persuasion allows the kindred to take blood by consent, under the guide of medical work or mutual kink.\n\nFarmer - Composure + Animal Ken is the roll to find and catch the chosen animal.\n\nOsiris - Manipulation + Subterfuge or Intimidation + Fame are both used to feed from the adoring fans.\n\nSandman - Dexterity + Stealth is for casing a location, breaking in and feeding without leaving a trace.\n\nScene Queen - Manipulation + Persuasion aids in feeding from those within the Kindred's subgroup, through conditioning and isolation to gain blood or gaslighting or forced silence.\n\nSiren - Charisma + Subterfuge is how sirens feed under the guise of sexual acts.\n\nExtortionist - Strength/Manipulation + Intimidation to feed through coercion.\n\nGraverobber - Resolve + Medicine for sifting through the dead for a body with blood. Manipulation + Insight for moving among miserable mortals.\n\nRoadside Killer - Dexterity/Charisma + Drive to feed by picking up down and outs with no other options.\n\nGrim Reaper - Intelligence + Awareness/Medicine in order to find victims.\n\nMontero - Intelligence + Stealth represents the expert planning of well-trained Retainers. Whereas a well-practiced plan and patient waiting is represented by Resolve + Stealth\n\nPursuer - Intelligence + Investigation to locate and find a victim no one will notice is gone. Stamina + Stealth for long stalking of unaware urban victims.\n\nTrapdoor - Charisma + Stealth for the victims that enter expecting a fun-filled night. Dexterity + Stealth to feed upon trespassers. Wits + Awareness + Haven dots is used to navigate the maze of the den itself.",

    "dice rolls" : "Frenzy\nWillpower + (Humanity/3)(rounded down)\n\nVitórias automáticas\nParada de dados é o Dobro do Desafio\n\nVencer a um custo\nRolagem que inclui sucessos, mas falha. Você pode alcançar seu objetivo, mas com algum custo.\n\nPegar Metade\nDivida seu total de dados pela metade (arredonde para baixo). Este será seu numero de sucessos.\n\nMúltiplos oponentes\nPerca um dado para cada ação sucessiva no mesmo turno.\n\nTeste estendido\nPode ser usado entre personagens\nTeste de dificuldade alta com rolagens acumulativas.\nE.g Colocar as mãos em uma relíquia exige três vitórias para cada tarefa:\nInt + Larceny - superar alarme\nDex + Larceny - Invadir local pela clarabóia\nComposure + Larceny - Extrair relíquia dentre laser de segurança\n\nRolagem única\nSe após 3 turnos de combate e a pergunta 'Algo mudará dramaticamente com mais interações?' não for respondida:\nDificuldade 3 para os jogadores tenham vencido no último turno.\nDif 4 se sofreram igual aos npc\ndif 5 se os npc tenham vencido\ndif 6 se os jogadores tiveram sorte de estar vivos.\n\nManobra\nO personagem estuda o adversário e se move para um lugar de vantagem, ou acerta num ponto crítico. Bônus de 1-3 dados.\n\nAtaque Total\n+1 de dano, mas não poderá defender nenhum ataque. Se for Arma a distância, descarrega a arma. (mesmo que o NPC tenha mais sucessos, ele ainda sofrerá todo dano.)\n\nDefesa Total\nPersonagem apenas quer sobreviver. Ganha um dado de bônus em todas as rolagens de defesa. Se estiver em boa cobertura, se torne imune a ataques a distância, contanto que não seja flanqueado (manobra). Só pode realizar ações menores." 
}

controle_updates = (
    "05/01/24: Adicionado: Rolagem de dados",
    "06/01/24: Adicionado: Gerador de Personagem",
    "07/01/24: Adicionado: Disciplinas no gerador de personagem",
    "09/01/24: Adicionado: Informações sobre clãs e disciplinas",
    "10/01/24: Atualizado: Rolagem de dados e corrigido limite de idade para Character Generator",
    "11/01/24: Atualizado: Nome das disciplinas, README, Informações sobre níveis das disciplinas. Adicionado: níveis de protean",
    "13/01/24: Adicionado: Easter Egg",
    "14/01/24: Atualizado: Disciplinas de Blood Stained Love",
    "22/01/24: Adicionado: Disciplinas de The Book of Nod Apocrypha",
)