easter_eggs_test = {
    'vampire':"We don't use the word 'Vampire'! What are you, an animal? No, you are a Kindred! A Kindred! Moderate your language!",
    
    'camarilla':"Camarilla? The Camarilla no longer exists! 2022 was the last year it existed in Porto Alegre. Do you know why?  Tell me, I want to know. They say the wizards messed up one of their charms and something happened. Do you know something?\nBut until we get answers:\n\nThe Camarilla is one of the most organized and influential Kindred organizations in history. Their goal is to preserve the masquerade and keep Kindred in line with rules that help protect their society from the prying mortal eye. Beyond this, it is a conspiracy to help elders preserve their power built on an undead secret society that influences global business and politics. The Camarilla is the closest thing they have to a system of government and an international union of cities. It is completed by an inner circle and its Justicars and Archons that roam the world to 'keep the peace'. A fierce moral stance is held on preserving humanity even against the impulses of the Blood, seeing themselves as shepherds to the herds of mortals they blindly control. Many Camarilla members have a wealth of power and money, on top of their age and the inclusion of Anarch defects joining their ranks makes the sect distinctly upper class.\n\nPredominate clan alignments: Banu Haqim, Lasombra, Malkavian, Nosferatu, Toreador, Tremere, Ventrue.",

    'anarchy':"They say that the Anarchy exists, that it surrounds humans as a helping hand,  an image to worship. But like every youth movement, perhaps it has died in oblivion. Decimated by her own sins.\n\nOriginally called the Anarch Revolt, this sect is as old as the revolution against the Camarilla itself. In recent decades it has seen vast growth as younger kindred find it increasingly difficult to understand why they must follow the laws of elders who care nothing for them, but to throw them in harms way when needed. All vampires who fall outside of the Tower's control are considered 'unbound', and the Anarch movement is a small but visible subsection of the unbound who, rather than hide, have decided to fight back. They fight to claim territory from those who oppress them, as the ancient hands that held onto it are disappearing due to the Beckoning or other outside forces.\n\nPredominate clan alignments: Brujah, Gangrel, The Ministry, Caitiff (sometimes).",

    'sabbat':'The Sabbat are monstrous creatures; vampire supremacists who see themselves above mortals and do not care for them. They are a sect that evokes fear at its mention with their ideologies being met with loathing. The Sword of Caine wages a war against the Antediluvians, a Gehenna War, seeking to claim revenge for Caine and the ancient betrayal done to him by his childer. Their goal is to destroy the Antediluvians and subject the mortal world to a world with vampires at the top.\nIn their effort to make themselves the ultimate predators they have ironically shackled themselves to the beast. The sect deindividualized, indoctrinated, and collectively Blood Bound each cainite in an effort to make fanatical members of their organization. With all that said, the Sabbat are far from a monolith. With many faces and takes on inhumane, it is easy to run into a variety of cainites from faction.\nThe Sabbat has shrunk in size in recent nights compared to the others. Due to the Lasombra exodus, the fierce Second Inquisition targeting from their breaches, the Anarchs and Camarilla willingness to combine efforts against the Sabbat, and with high Final Death rate due to the Gehenna War the sects find many sources of peril in modern nights. Even then the challenge only enhances their fervor.',

    'poabynight':'Want to know more? www.poabynight.com.br!',

    'disciplines':'Want to know more about the disciplines? Type  the name or level in the chat and you will receive the same information that is on vtm.paradoxwikis.com',

    "diablerie":"I am disgusted that you would even think of searching for this term.\nDiablerie is an act condemned by most of us, as it involves not only drinking another vampire dry, but also consuming his soul, his essence, his consciousness. It is such a nefarious act that it corrupts you, that it leaves you visible to those who have Auspex, with dark spots in your aura. But since you're interested, I'll teach you.\n\nTo commit diablerie, you restrain the victim in some way and drink them, the greatest pleasure you will feel in your life. Once the prey is exhausted, you can attempt to commit the ultimate blasphemy and take their soul. It is a contest against taking upon oneself one's own nature and power; If you succeed, the diablerie begins and, at this cost, by gaining power, you lose Humanity, getting closer to the beast. If you fail, you will be one step closer to Final Death, after all, you fought with your own soul.\n\nFirst step: Strength + Resolve (Dif. 3) sometimes the number of Blood Potency\nSecond step: Humanity + your own Blood Potency vs. Resolve + Victim's Blood Potency.\n\nMake the most of your exp.",
    
    'humanity':"We are monsters. We are monsters to the point of creating a scale to measure our humanity. The most interesting thing is that on a scale of 0 to 10, most Kindred stabilize at grade 5, neither beast nor human. They say we start with 7, but who am I to question the humanity of a body that is still warm, that is nourished by the sun and smiles when the day is over. We are monsters, regardless of this classification, and even the holiest can be morally corrupt (this one's for you Salubri).\nAs we get older, time corrupts us and connections with life are lost when everyone we know is dead. When we see, a corpse is just another corpse and thus, we go down a step in humanity.",
    
    "final death":"It's your second death. It's your real goodbye. But don't be scared, you've already died as a human, now as Kindred, but there's still one more death to go. When everyone who once knew you forgets who you are.",
}

feedingComplications1 = ("Alleycat\n- Never Easy: The predator falls while closing in on their prey, alerting the target who then retaliates. The player must fight the prey to feed, with the risk of a failure resulting in the prey escaping and potentially causing a breach of the masquerade.\n- Bait and Switch: The prey turns out to be hunting the predator instead, armed with a rifle. The player must decide whether to flee or confront the threat, with a test of composure and awareness to locate the shooter.\n- Undercover: The predator attacks a seemingly easy target, only to realize they are an undercover cop with body armor and a firearm. The player must decide whether to retreat or engage, to evade capture or further conflict.\n",
"Bagger\n- Changing Agent: The player encounters a different individual than their usual contact while trying to procure blood. They must assess the situation to determine if it's a trap or a genuine misunderstanding.\n- New Codes: Accessing a blood bank becomes more challenging due to upgraded security measures. The player must decide whether to use force or persuasion to gain entry, or to convince someone else to assist. Long-term security clearance upgrades may require hacking skills.\n- Emergency Room: A hospital is overwhelmed with casualties from a major incident, offering an opportunity for the player to obtain blood. However, the limited blood supply is closely monitored, requiring stealth to acquire it without drawing attention. The player must balance their needs with the potential consequences of taking blood meant for saving lives.\n",
"Blood Leech\n- Escape: The captive vampire manages to break free, posing a potential threat if they reveal the player's existence to others. The player must track them down quickly, while remaining vigilant against potential ambushes. Recapturing the escaped vampire may involve combat with them or any allies assisting them.\n- Neonate: The player encounters a newly sired vampire wandering the city streets, potentially lost or abandoned. As they likely don't belong to the player's sect, the player sees an opportunity to gain their trust and potentially exploit their knowledge.\n",
"Cleaver\n- Recital: A child in the player's adopted family has an important evening recital at school, and they want the player to attend. However, the timing conflicts with the player's waking hours, potentially leaving them hungry and vulnerable in a room full of mortals. Despite the challenges, attending the recital offers an opportunity to feed discreetly.\n- Nightmares: A regular member of the player's herd recoils in horror when the player attempts to feed on them. They have been experiencing intense nightmares related to the feeding experiences, and any attempt to feed triggers these memories. The herd member requires therapy to address the issue.\n",
"Consensualist\n- Uninformed Consent: The victim initially consents to exchanging blood, believing it to be part of a vampire roleplay. However, when the player reveals their true nature by biting them, the victim panics and screams in terror. The player must decide how to handle the situation:\n- Physical Restraint: The player can choose to physically restrain the victim to keep them quiet. A test of strength and brawl is required to restrain them successfully. If the player fails, the victim will attempt to flee.\n- Calm and Explanation: Alternatively, the player can attempt to calm the victim down and explain the situation.\n",)

feedingComplications2 = ("Farmer\n- Dual Hunt: While tracking prey, the player realizes they are not the only hunter. Another predator, such as a feral dog or a mountain lion, is also targeting the same prey. The player must decide whether to compete for the prey or to turn their attention towards hunting the other predator instead.\n- Sudden Reversal: During a hunt for usual animal prey, the player discovers that their predations have caused the prey species to band together for protection. As the player closes in on a lone target, they are ambushed by several members of the same species. The intensity of the attack varies based on the size of the prey, with larger prey resulting in fewer attackers but smaller prey attacking as a swarm.\n",
"Osiris\n- Strange Mark: The player notices a mysterious symbol on members of their herd, who seem unaware of its origin. The player must investigate the meaning of the symbol and determine if their herd is involved in a secret faction or if they are being targeted by another Osiris.\n- Paparazzi: While feeding in seclusion, the player is interrupted by a paparazzi attempting to capture an exclusive picture. The player must stop feeding to pursue the intruder, track them down, and either confront them in combat or persuade them to delete the pictures.\n- New Member: The player discovers a change in the taste and quality of their herd's blood, leading to heightened emotions after feeding. Investigation reveals that a spirit inhabits the blood, feeding off anger and rage. The player must decide whether to rid themselves of the spirit, potentially leading to a focused storyline.\n",
"Sandman\n- Small Interruption: While feeding on a sleeping victim, the player is interrupted by a wide-eyed little girl who has unexpectedly entered the room. The player must quickly come up with a convincing explanation to reassure the child and convince her to return to bed without raising alarm.\n- Tainted Well: The player discovers that their sleeping victim has been drugged, causing them to fall under the influence of the substance. The player must resist the effects of the drug to avoid passing out and potentially being discovered.\n",
"Scene Queen\n- Unexpected Bargaining: The prey, once willing to be fed upon, now demands something in return due to the player's perceived decline in social status within the scene. The player must negotiate a deal to continue feeding, using persuasion or manipulation skills to offer something of value in exchange for their continued cooperation.\n- Overcome: A potential victim is deeply impressed by the player, making them easy prey but difficult to obtain consent from due to their overwhelming awe. Tests involving charisma are automatically successful, but the player must gauge their potential reaction to witnessing the player's true nature and impress upon them the need for secrecy.\n- Pretender: The prey, new to the scene, desires to become the player's blood doll but lacks the necessary understanding or appearance to fit in. The player must decide whether to integrate them into their social circle, risking their own status, or educate and groom them to better fit in.\n",
"Siren\n- Bonus Guest: The player seduces a new prey into bringing them back to their place, only to be caught in the act by the partner returning unexpectedly. The player must attempt to convince the partner that they are just a fling to avoid a masquerade breach, but tensions escalate regardless. Convincing the partner to join them is possible but challenging, and hiding the player's true nature from both partners simultaneously adds to the difficulty.\n- Dom to Sub: The player's conquest turns the tables by handcuffing them to the bed and revealing their desire for a more dominant role. If the player submits, they may face brutal treatment without the option of a safe word. Tests involve breaking free from the restraints, or enduring the encounter without getting too hurt. Attempting to feed in this situation requires a difficult test.")

controle_updates = (
     "01/05/24: Add: Dice Roll",
     "06/01/24: Add: Character Generator",
     "07/01/24: Add: Disciplines in the character generator",
     "09/01/24: Add: Information about clans and disciplines",
     "01/10/24: Fix: Dice roll and corrected age limit for Character Generator",
     "01/11/24: Fix: Name of subjects, README, Information about discipline levels. Add: protean levels",
     "01/13/24: Add: Easter Egg",
     "01/14/24: Fix: Blood Stained Love Disciplines",
     "01/22/24: Add: Book of Nod Apocrypha Disciplines",
     "01/23/24: Fix: Limit of 20 dice per roll and roll error message",
     "25/01/24: Add: Easter eggs",
     "02/02/24: Add: Resonance",
     "26/03/24: Add: English translation of all texts",
     "27/03/24: Fix: English translation. Add: Easter Eggs",
     "01/04/24: Fix: Async options"
)