easter_eggs_test = {
    'vampiro':'Nós não usamos a palavra "Vampiro"! O que você é, um animal? Não, você é um Kindred, um Membro. Modere o linguajar!',
    'camarilla':"Camarilla? A Camarilla não existe mais! 2022 foi o último ano que ela existiu em Porto Alegre. Sabe por quê? Então, me conta, eu também queria saber. Dizem que os magos erram a mão em um de seus encantos e algo aconteceu. Você sabe de alguma coisa?",
    'anarquia':"Dizem que ela existe, que ela ronda os humanos como uma mão amiga, um ombro para se chorar, uma imagem para adorar.Mas como todo movimento juvenil, talvez ela tenha morrido no esquecimento. Dizimada pelos próprios pecados.",
    'poabynight':'Quer saber mais? www.poabynight.com.br!',
    'disciplinas':'Quer saber mais sobre as disciplinas? Coloca o nome delas em inglês aqui no chat que você vai receber a mesma informações que estão no vtm.paradoxwikis.com',
    "diablerie":"Tenho nojo por você pensar em pesquisar por este termo.\nA Diablerie é um ato condenado pela maioria de nós, já que envolve não apenas beber até secar outro vampiro, mas também roubar sua a sua alma, sua essência, sua consciência. É um ato tão nefasto que te corrompe, que te deixa visível para quem tem Auspícios, com manchas escuras na sua aura. Mas já que você tem interesse, eu vou te ensinar.\n\nPara cometer a diablerie, você restringe a vítima de alguma maneira e a bebe. O maior prazer que você vai sentir nessa sua vida. Uma vez que a presa esteja esgotada, você pode tentar cometer a blasfêmia final e levar a sua alma. É uma competição contra tomar para si sua própria natureza e poder; caso você tenha sucesso, a diablerie começa e, por esse custo, pelo ganho de poder, você perda Humanidade, se aproximando da besta. Caso falhe, você estará um passo mais próximo da Morte Final, afinal, você lutou com a própria alma.\n\nPrimeiro passo: Strength + Resolve (Dif. 3) por vezes o numero de Blood Potency\nSegundo passo: Humanity + a própria Blood Potency vs. Resolve + Blood Potency da vítima.\n\nAproveite sua exp.",
    'humanidade':"Nós somos monstros. Somos monstros a ponto de criar uma escala para medir nossa humanidade. O mais interessante é que numa escala de 0 a 10, a maioria dos Kindred estabiliza no grau 5, nem besta, nem humano. Dizem que nós começamos com 7, mas quem sou eu para questionar a humanidade de um corpo ainda quente, que se nutre com o sol e sorri quando o dia acaba. Nós somos monstros, independente desta classificação, e até os mais santos podem ser moralmente corruptos (essa é pra vocês Salubri).\nA medida que ficamos velhos, o tempo nos corrompe e as ligações com a vida se perdem quando todos os que conhecemos estão mortos. Quando vemos, um cadáver é apenas mais um cadáver e assim, nós descemos um degrau na humanidade.",
    "morte final":"É a sua segunda morte. É o seu verdadeiro adeus. Mas não se assuste, você já morreu como humano, agora como Kindred, mas ainda falta mais uma morte. Quando todos aqueles que um dia te conheceram, esquecerem de quem você é.",

    "predator type roll" :"Alleycat - Strength + Brawl is to take blood by force or threat. Wits + Streetwise can be used to find criminals as if a vigilante figure.\n\nBagger - Intelligence + Streetwise can be used to find, gain access and purchase the goods.\n\nBlood Leech - This Predator Type is suggested to not be abstracted down to a dice pool.\n\nCleaver - Manipulation + Subterfuge is used to condition the victims, socializing with them and feeding from them without the cover being blown.\n\nConsensualist - Manipulation + Persuasion allows the kindred to take blood by consent, under the guide of medical work or mutual kink.\n\nFarmer - Composure + Animal Ken is the roll to find and catch the chosen animal.\n\nOsiris - Manipulation + Subterfuge or Intimidation + Fame are both used to feed from the adoring fans.\n\nSandman - Dexterity + Stealth is for casing a location, breaking in and feeding without leaving a trace.\n\nScene Queen - Manipulation + Persuasion aids in feeding from those within the Kindred's subgroup, through conditioning and isolation to gain blood or gaslighting or forced silence.\n\nSiren - Charisma + Subterfuge is how sirens feed under the guise of sexual acts.\n\nExtortionist - Strength/Manipulation + Intimidation to feed through coercion.\n\nGraverobber - Resolve + Medicine for sifting through the dead for a body with blood. Manipulation + Insight for moving among miserable mortals.\n\nRoadside Killer - Dexterity/Charisma + Drive to feed by picking up down and outs with no other options.\n\nGrim Reaper - Intelligence + Awareness/Medicine in order to find victims.\n\nMontero - Intelligence + Stealth represents the expert planning of well-trained Retainers. Whereas a well-practiced plan and patient waiting is represented by Resolve + Stealth\n\nPursuer - Intelligence + Investigation to locate and find a victim no one will notice is gone. Stamina + Stealth for long stalking of unaware urban victims.\n\nTrapdoor - Charisma + Stealth for the victims that enter expecting a fun-filled night. Dexterity + Stealth to feed upon trespassers. Wits + Awareness + Haven dots is used to navigate the maze of the den itself.",

    "dice rolls" : "Frenzy\nWillpower + (Humanity/3)(rounded down)\n\nVitórias automáticas\nParada de dados é o Dobro do Desafio\n\nVencer a um custo\nRolagem que inclui sucessos, mas falha. Você pode alcançar seu objetivo, mas com algum custo.\n\nPegar Metade\nDivida seu total de dados pela metade (arredonde para baixo). Este será seu numero de sucessos.\n\nMúltiplos oponentes\nPerca um dado para cada ação sucessiva no mesmo turno.\n\nTeste estendido\nPode ser usado entre personagens\nTeste de dificuldade alta com rolagens acumulativas.\nE.g Colocar as mãos em uma relíquia exige três vitórias para cada tarefa:\nInt + Larceny - superar alarme\nDex + Larceny - Invadir local pela clarabóia\nComposure + Larceny - Extrair relíquia dentre laser de segurança\n\nRolagem única\nSe após 3 turnos de combate e a pergunta 'Algo mudará dramaticamente com mais interações?' não for respondida:\nDificuldade 3 para os jogadores tenham vencido no último turno.\nDif 4 se sofreram igual aos npc\ndif 5 se os npc tenham vencido\ndif 6 se os jogadores tiveram sorte de estar vivos.\n\nManobra\nO personagem estuda o adversário e se move para um lugar de vantagem, ou acerta num ponto crítico. Bônus de 1-3 dados.\n\nAtaque Total\n+1 de dano, mas não poderá defender nenhum ataque. Se for Arma a distância, descarrega a arma. (mesmo que o NPC tenha mais sucessos, ele ainda sofrerá todo dano.)\n\nDefesa Total\nPersonagem apenas quer sobreviver. Ganha um dado de bônus em todas as rolagens de defesa. Se estiver em boa cobertura, se torne imune a ataques a distância, contanto que não seja flanqueado (manobra). Só pode realizar ações menores.",

    "resonance":"\n\nCholeric\nThe humor of passion and anger but also one of jealousy and violence. This Resonance can, but not exclusively, be found in vessels that have the will to fight back against whatever problems they face\nEmotions: Angry, violent, bullying, passionate or envious.\nDisciplines: Celerity and Potence.\n\nMelancholy\nThe humor of sadness and the downtrodden but also those who seek enlightenment. This Resonance can, but not exclusively, be found in vessels who have lost the will to fight or those who are seized by the gain of knowledge.\nEmotions: Sad, scared, depressed, intellectual, or grounded.\nDisciplines: Fortitude and Obfuscate.\n\nPhlegmatic\nThe humor of those who are calm and relaxed or those who are lost in their own reminiscing. This Resonance can, but not exclusively, be found in vessels who are at peace or can't find a reason to care at the moment.\nEmotions: Lazy, apathetic, calm, controlling, and sentimental.\nDisciplines: Auspex and Dominate.\n\nSanguine\nThe humor of sex and passion but also of happiness and liveliness. This Resonance can, but not exclusively, be found in vessels who have a sexual interest in the vampire or are simply enjoying life itself.\nEmotions: Horny, happy, enthusiastic, addicted, active, and flighty.\nDisciplines: Blood Sorcery and Presence.\n\n'Empty'\nThis Resonance represents those who lack general emotions.\nEmotions: That of sociopaths or the emotionally detached.\nDisciplines: Oblivion.\n\nAnimal Blood\nWhile not a Resonance, it does serve a purpose to vampires. Giving them access to the last two Disciplines of Animalism and Protean. The Storyteller is free to correlate animal blood to the main four Resonances, should they find it important to their chronicle." ,
}

controle_updates = (
    "05/01/24: Add: Rolagem de dados",
    "06/01/24: Add: Gerador de Personagem",
    "07/01/24: Add: Disciplinas no gerador de personagem",
    "09/01/24: Add: Informações sobre clãs e disciplinas",
    "10/01/24: Fix: Rolagem de dados e corrigido limite de idade para Character Generator",
    "11/01/24: Fix: Nome das disciplinas, README, Informações sobre níveis das disciplinas. Adicionado: níveis de protean",
    "13/01/24: Add: Easter Egg",
    "14/01/24: Fix: Disciplinas de Blood Stained Love",
    "22/01/24: Add: Disciplinas de The Book of Nod Apocrypha",
    "23/01/24: Fix: Limite de 30 dados por rolagem e mensagem de erro de rolagem",
    "25/01/24: Add: Easter eggs.",
    "20/02/24: Add: Resonance",
)